#!/bin/sh

# Activate commit message pattern
ENABLE_PATTERN=true

# Insert your JIRA key below, like this "KEY1 KEY2 KEY3".
PROJECT_JIRA_KEYS=""
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $1)

# Replace space with | to create the regex pattern
KEYS=$(echo "$PROJECT_JIRA_KEYS" | tr ' ' '|')

# REGEX to ensure that will have one or two JIRA tasks ID in the comment.
PATTERN="^\[($KEYS)-[0-9]{1,6}\](\[($KEYS)-[0-9]{1,6}\])? (feat|fix|docs|style|refactor|perf|test|chore): .+$"

if [ "$ENABLE_PATTERN" = true ]; then
  if ! echo "$COMMIT_MSG" | grep -Eq "$PATTERN"; then
      echo "ERROR: Your commit message doesn't match with our pattern."
      echo "======================================================================================="
      echo "HINT: Commit types ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore']"
      echo "HINT: You can include one or two Jira tasks"
      echo "HINT: Valid commit message example_1: [$KEYS-123] feat: Implements something"
      echo "HINT: Valid commit message example_2: [$KEYS-123][$KEYS-321] fix: Solving something"
      exit 1
  fi
else
    echo "INFO: Commit message pattern check is disabled."
fi